// This file is auto-generated by @hey-api/openapi-ts

export type Body_files_upload_file_endpoint = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FilePublic = {
    filename: string;
    content_type: string;
    size?: (number | null);
    job_id?: (string | null);
    job_status?: (string | null);
    id: string;
    created_at?: (string | null);
    user_id: string;
};

export type FilesPublic = {
    data: Array<FilePublic>;
    count: number;
};

export type FilesStatusRequest = {
    file_ids: Array<(string)>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    user_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
};

export type UserPublic = {
    id: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserStorageStatPublic = {
    id: string;
    user_id: string;
    file_count: number;
    total_size: number;
    total_cost: number;
    updated_at: string;
    total_transactions: number;
    total_pages?: (number | null);
};

export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type FilesUploadFileEndpointData = {
    formData: Body_files_upload_file_endpoint;
};

export type FilesUploadFileEndpointResponse = (FilePublic);

export type FilesListFilesData = {
    limit?: number;
    skip?: number;
};

export type FilesListFilesResponse = (FilesPublic);

export type FilesUpdateFileJobStatusEndpointData = {
    fileId: string;
    jobStatus: string;
};

export type FilesUpdateFileJobStatusEndpointResponse = (unknown);

export type FilesGetFileStatusData = {
    fileId: string;
};

export type FilesGetFileStatusResponse = (FilePublic);

export type FilesDownloadTableExcelFileData = {
    fileId: string;
};

export type FilesDownloadTableExcelFileResponse = (unknown);

export type FilesGetFilesBatchStatusData = {
    requestBody: FilesStatusRequest;
};

export type FilesGetFilesBatchStatusResponse = (FilesPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemEndpointData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemEndpointResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemEndpointData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemEndpointResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type StoragesGetMyStorageStatResponse = (UserStorageStatPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserEndpointData = {
    requestBody: UserCreate;
};

export type UsersCreateUserEndpointResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserEndpointData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserEndpointResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsClearAllFilesResponse = (Message);