"""Edit User Model

Revision ID: 312239f38f57
Revises: 029973b1ef8d
Create Date: 2026-03-24 00:46:52.854728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '312239f38f57'
down_revision = '029973b1ef8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
