"""edit-model-1

Revision ID: 315fb0cb1b81
Revises: 1b631ae321a9
Create Date: 2026-03-25 23:04:09.443022

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '315fb0cb1b81'
down_revision = '1b631ae321a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('files', sa.Column('job_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_files_job_id'), 'files', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_job_id'), table_name='files')
    op.drop_column('files', 'job_status')
    op.drop_column('files', 'job_id')
    # ### end Alembic commands ###
