"""edit-model-3

Revision ID: 3978fdec9e0b
Revises: 998082d0b0f6
Create Date: 2026-03-26 22:39:08.473449

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3978fdec9e0b'
down_revision = '998082d0b0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('err_msg', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'err_msg')
    # ### end Alembic commands ###
