"""edit-model-2

Revision ID: 998082d0b0f6
Revises: 315fb0cb1b81
Create Date: 2026-03-26 12:35:42.111724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '998082d0b0f6'
down_revision = '315fb0cb1b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('bank', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'bank')
    # ### end Alembic commands ###
