"""remove-relationship

Revision ID: b6a0bfbb9e6d
Revises: c6971f55aa53
Create Date: 2026-03-25 00:45:07.598264

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b6a0bfbb9e6d'
down_revision = 'c6971f55aa53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
