"""Add api key model 

Revision ID: c4f659581040
Revises: b27c541d6090
Create Date: 2026-04-12 13:44:09.876423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c4f659581040'
down_revision = 'b27c541d6090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_storage_stats', 'total_pages',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_storage_stats', 'total_pages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('files', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
